name: Release Build

on:
  push:
    paths-ignore: 
      - '.github/**'
    branches: [ "master" ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout master repo
      uses: actions/checkout@v3
    
    - name: Setup java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin
    
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        
    - name: version
      run: echo "::set-output name=version::$(java -jar $(ls /build/libs/*.jar | sort | tail -n1) --version)"
      id: version
    
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      with:
        draft: true
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: upload artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: $(ls /build/libs/*.jar | sort | tail -n1)
        asset_name: $(ls /build/libs/*.jar | sort | tail -n1)
        asset_content_type: application/jar-archive
      env:
        GITHUB_TOKEN: ${{ github.token }}
